# Use the official Ubuntu image as the base
FROM ubuntu:latest

# Install ca-certificates, necessary tools, NVIDIA GPG key, and repository
RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates \
    curl \
    gnupg2 \
    && curl -fsSL https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/3bf863cc.pub | apt-key add - \
    && echo "deb https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/ /" > /etc/apt/sources.list.d/cuda.list \
    && apt-get update

# Install CUDA toolkit
RUN apt-get install -y --no-install-recommends cuda-toolkit-11-2 \
    && rm -rf /var/lib/apt/lists/*

# Install Python, pip, and git
RUN apt-get update && apt-get install -y --no-install-recommends \
    python3 \
    python3-pip \
    git \
    && rm -rf /var/lib/apt/lists/*

#DBN 
ADD ml/repos/deep-belief-network/requirements.txt requirements.txt
RUN pip install -r requirements.txt

#DBN with pytorch
ADD ml/repos/Deep-Belief-Networks-in-PyTorch/DBN.py DBN.py

# Set an environment variable for CUDA
ENV PATH=/usr/local/cuda-11.2/bin:${PATH}
ENV LD_LIBRARY_PATH=/usr/local/cuda-11.2/lib64:${LD_LIBRARY_PATH}

# Command to keep the container running indefinitely
CMD ["tail", "-f", "/dev/null"]
